using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using RD.Domain;
using RD.Domain.Entities;

namespace RD.Infrastructure;

public class AppUser : IdentityUser { }

/// <summary>
/// Always resolve via IDbContextFactory&lt;RdDbContext&gt; — Blazor circuits are
/// long-lived and concurrent; Hangfire jobs get one context per execution.
/// All timestamps are datetimeoffset (UTC). Enums persist as strings with
/// CHECK constraints generated by EF's converters + max lengths.
/// </summary>
public class RdDbContext(DbContextOptions<RdDbContext> options) : IdentityDbContext<AppUser>(options)
{
    public DbSet<Client> Clients => Set<Client>();
    public DbSet<TrialPeriod> TrialPeriods => Set<TrialPeriod>();
    public DbSet<IdentityLink> IdentityLinks => Set<IdentityLink>();
    public DbSet<MappingVerification> MappingVerifications => Set<MappingVerification>();
    public DbSet<Package> Packages => Set<Package>();
    public DbSet<PackageVersion> PackageVersions => Set<PackageVersion>();
    public DbSet<LedgerEntry> LedgerEntries => Set<LedgerEntry>();
    public DbSet<Decision> Decisions => Set<Decision>();
    public DbSet<InvestigationItem> InvestigationItems => Set<InvestigationItem>();
    public DbSet<OutboxAction> OutboxActions => Set<OutboxAction>();
    public DbSet<DunningCase> DunningCases => Set<DunningCase>();
    public DbSet<DunningAttempt> DunningAttempts => Set<DunningAttempt>();
    public DbSet<PauseOperation> PauseOperations => Set<PauseOperation>();
    public DbSet<WebhookInboxItem> WebhookInbox => Set<WebhookInboxItem>();
    public DbSet<SyncRun> SyncRuns => Set<SyncRun>();
    public DbSet<KillSwitchState> KillSwitch => Set<KillSwitchState>();
    public DbSet<AlertLogEntry> AlertLog => Set<AlertLogEntry>();
    public DbSet<StripeSubscriptionProj> StripeSubscriptions => Set<StripeSubscriptionProj>();
    public DbSet<StripeInvoiceProj> StripeInvoices => Set<StripeInvoiceProj>();
    public DbSet<MetaCampaignProj> MetaCampaigns => Set<MetaCampaignProj>();
    public DbSet<MetaInsightDailyProj> MetaInsightsDaily => Set<MetaInsightDailyProj>();
    public DbSet<GhlMessageProj> GhlMessages => Set<GhlMessageProj>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        base.OnModelCreating(b);

        // Enums as strings for readability + CHECK-able values.
        b.Entity<Client>(e =>
        {
            e.Property(x => x.BusinessName).HasMaxLength(200);
            e.Property(x => x.ContactName).HasMaxLength(200);
            e.Property(x => x.Email).HasMaxLength(320);
            e.Property(x => x.Phone).HasMaxLength(40);
            e.Property(x => x.Country).HasMaxLength(2);
            e.Property(x => x.CurrencyCode).HasMaxLength(3).IsUnicode(false);
            e.Property(x => x.ContractType).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.AccountType).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.EnforcementMode).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.RowVersion).IsRowVersion();
            e.HasOne(x => x.Package).WithMany().HasForeignKey(x => x.PackageId).OnDelete(DeleteBehavior.Restrict);
        });

        b.Entity<TrialPeriod>(e =>
        {
            e.Property(x => x.Outcome).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.SpendCapSnapshot).HasPrecision(19, 4);
            e.HasOne(x => x.Client).WithMany(c => c.TrialPeriods).HasForeignKey(x => x.ClientId).OnDelete(DeleteBehavior.Restrict);
            e.HasIndex(x => new { x.ClientId, x.StartsAt });
        });

        b.Entity<IdentityLink>(e =>
        {
            e.Property(x => x.System).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.Kind).HasConversion<string>().HasMaxLength(15);
            e.Property(x => x.ExternalId).HasMaxLength(100);
            e.HasOne(x => x.Client).WithMany(c => c.IdentityLinks).HasForeignKey(x => x.ClientId).OnDelete(DeleteBehavior.Restrict);
            // AdAccount is a SHARED identity (the master ad account backs ~177 clients) — uniqueness applies to the truly per-client kinds.
            // This still guarantees a given Stripe customer/subscription belongs to exactly ONE client.
            e.HasIndex(x => new { x.System, x.Kind, x.ExternalId }).IsUnique().HasFilter("[Kind] <> 'AdAccount'");
            // Cardinality: one ACTIVE GHL Contact per client. Stripe Customer/Subscription are
            // deliberately NOT constrained here — one business legitimately owns several Stripe
            // accounts/subscriptions (verified live), and all of them link to the one client so
            // every account is monitored. Campaigns were always many-per-client.
            e.HasIndex(x => new { x.ClientId, x.System, x.Kind })
                .IsUnique()
                .HasFilter("[InvalidatedAt] IS NULL AND [Kind] = 'Contact'");
        });

        b.Entity<MappingVerification>(e =>
        {
            e.Property(x => x.VerifiedBy).HasMaxLength(100);
            e.HasOne(x => x.Client).WithMany().HasForeignKey(x => x.ClientId).OnDelete(DeleteBehavior.Restrict);
            e.HasIndex(x => new { x.ClientId, x.VerifiedAt });
        });

        b.Entity<Package>(e => e.Property(x => x.Name).HasMaxLength(100));
        b.Entity<PackageVersion>(e =>
        {
            e.Property(x => x.CurrencyCode).HasMaxLength(3).IsUnicode(false);
            e.Property(x => x.OfferName).HasMaxLength(200);
            e.Property(x => x.CreatedBy).HasMaxLength(100);
            e.Property(x => x.DailyRate).HasPrecision(19, 4);
            e.Property(x => x.DailyBudget).HasPrecision(19, 4);
            e.Property(x => x.TrialSpendCap).HasPrecision(19, 4);
            e.HasOne(x => x.Package).WithMany(p => p.Versions).HasForeignKey(x => x.PackageId).OnDelete(DeleteBehavior.Restrict);
            e.HasIndex(x => new { x.PackageId, x.EffectiveFrom }).IsUnique();
        });

        b.Entity<LedgerEntry>(e =>
        {
            e.Property(x => x.Type).HasConversion<string>().HasMaxLength(15);
            e.Property(x => x.SourceSystem).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.SourceObjectId).HasMaxLength(120);
            e.Property(x => x.CurrencyCode).HasMaxLength(3).IsUnicode(false);
            e.Property(x => x.SignedAmount).HasPrecision(19, 4);
            e.HasIndex(x => new { x.ClientId, x.OccurredAt });
            // Ingestion idempotency: polling + webhooks can never double-count money.
            e.HasIndex(x => new { x.SourceSystem, x.SourceObjectId, x.Type }).IsUnique();
        });

        b.Entity<Decision>(e =>
        {
            e.Property(x => x.PolicyVersion).HasMaxLength(30);
            e.Property(x => x.ProposedAction).HasConversion<string>().HasMaxLength(15);
            e.Property(x => x.Mode).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.Reason).HasMaxLength(500);
            e.HasIndex(x => new { x.ClientId, x.EvaluatedAt });
        });

        b.Entity<InvestigationItem>(e =>
        {
            e.Property(x => x.Kind).HasConversion<string>().HasMaxLength(30);
            e.Property(x => x.Status).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.Detail).HasMaxLength(1000);
            e.Property(x => x.ResolvedBy).HasMaxLength(100);
            e.Property(x => x.ResolutionNote).HasMaxLength(1000);
            e.HasIndex(x => new { x.Status, x.Kind });
        });

        b.Entity<OutboxAction>(e =>
        {
            e.Property(x => x.ActionType).HasConversion<string>().HasMaxLength(25);
            e.Property(x => x.Status).HasConversion<string>().HasMaxLength(20);
            e.Property(x => x.ApprovalChannel).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.IdempotencyKey).HasMaxLength(200);
            e.Property(x => x.ApprovedBy).HasMaxLength(100);
            e.Property(x => x.DismissReason).HasMaxLength(500);
            e.Property(x => x.LeaseOwner).HasMaxLength(100);
            e.Property(x => x.LastError).HasMaxLength(2000);
            // Nullable notify-once marker for the Slack notifier (maps to a single nullable datetimeoffset column).
            e.Property(x => x.SlackNotifiedAt);
            e.Property(x => x.RowVersion).IsRowVersion();
            e.HasIndex(x => x.IdempotencyKey).IsUnique();
            e.HasIndex(x => new { x.Status, x.NotBefore, x.LeaseUntil });
            e.HasIndex(x => new { x.SequenceGroup, x.SequenceNo });
        });

        b.Entity<DunningCase>(e =>
        {
            e.Property(x => x.InvoiceExternalId).HasMaxLength(100);
            e.Property(x => x.Status).HasConversion<string>().HasMaxLength(15);
            // One OPEN case per invoice.
            e.HasIndex(x => x.InvoiceExternalId).IsUnique().HasFilter("[Status] = 'Open'");
            e.HasIndex(x => new { x.ClientId, x.Status });
        });

        b.Entity<DunningAttempt>(e =>
        {
            e.Property(x => x.VendorMessageId).HasMaxLength(100);
            e.Property(x => x.FailureReason).HasMaxLength(500);
            e.HasOne(x => x.Case).WithMany(c => c.Attempts).HasForeignKey(x => x.DunningCaseId).OnDelete(DeleteBehavior.Restrict);
            e.HasIndex(x => new { x.DunningCaseId, x.Step }).IsUnique();
        });

        b.Entity<PauseOperation>(e =>
        {
            e.Property(x => x.EntityType).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.ExternalId).HasMaxLength(100);
            e.Property(x => x.PriorStatus).HasMaxLength(30);
            e.Property(x => x.RemoteVersion).HasMaxLength(100);
            e.Property(x => x.State).HasConversion<string>().HasMaxLength(20);
            e.HasIndex(x => new { x.OutboxActionId, x.EntityType, x.ExternalId }).IsUnique();
            e.HasIndex(x => new { x.ClientId, x.State });
        });

        b.Entity<WebhookInboxItem>(e =>
        {
            e.Property(x => x.System).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.ExternalEventId).HasMaxLength(120);
            e.Property(x => x.EventType).HasMaxLength(100);
            e.Property(x => x.EntityRef).HasMaxLength(120);
            e.Property(x => x.Status).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.LastError).HasMaxLength(2000);
            e.HasIndex(x => new { x.System, x.ExternalEventId }).IsUnique();
            e.HasIndex(x => new { x.Status, x.ReceivedAt });
        });

        b.Entity<SyncRun>(e =>
        {
            e.Property(x => x.System).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.Status).HasConversion<string>().HasMaxLength(10);
            e.Property(x => x.Error).HasMaxLength(2000);
            e.HasIndex(x => new { x.System, x.StartedAt });
        });

        b.Entity<KillSwitchState>(e =>
        {
            e.Property(x => x.Id).ValueGeneratedNever();
            e.Property(x => x.Actor).HasMaxLength(100);
            e.Property(x => x.Reason).HasMaxLength(500);
            e.Property(x => x.RowVersion).IsRowVersion();
            e.ToTable(t => t.HasCheckConstraint("CK_KillSwitch_Singleton", "[Id] = 1"));
        });

        b.Entity<AlertLogEntry>(e =>
        {
            e.Property(x => x.Severity).HasMaxLength(10);
            e.Property(x => x.Message).HasMaxLength(2000);
            e.HasIndex(x => new { x.SlackDelivered, x.EmailDelivered, x.CreatedAt });
        });

        // Projections: vendor-keyed, no FK to Client (links resolve via IdentityLink) — Restrict-by-convention.
        b.Entity<StripeSubscriptionProj>(e =>
        {
            e.HasKey(x => x.SubscriptionId);
            e.Property(x => x.SubscriptionId).HasMaxLength(100);
            e.Property(x => x.CustomerId).HasMaxLength(100);
            e.Property(x => x.Status).HasMaxLength(30);
            e.Property(x => x.PriceInterval).HasMaxLength(10);
            e.Property(x => x.Amount).HasPrecision(19, 4);
            e.Property(x => x.CurrencyCode).HasMaxLength(3).IsUnicode(false);
            e.HasIndex(x => x.ClientId);
        });
        b.Entity<StripeInvoiceProj>(e =>
        {
            e.HasKey(x => x.InvoiceId);
            e.Property(x => x.InvoiceId).HasMaxLength(100);
            e.Property(x => x.CustomerId).HasMaxLength(100);
            e.Property(x => x.SubscriptionId).HasMaxLength(100);
            e.Property(x => x.Status).HasMaxLength(30);
            e.Property(x => x.AmountDue).HasPrecision(19, 4);
            e.Property(x => x.AmountPaid).HasPrecision(19, 4);
            e.Property(x => x.CurrencyCode).HasMaxLength(3).IsUnicode(false);
            e.Property(x => x.HostedInvoiceUrl).HasMaxLength(500);
            e.HasIndex(x => new { x.ClientId, x.Status });
        });
        b.Entity<MetaCampaignProj>(e =>
        {
            e.HasKey(x => x.CampaignId);
            e.Property(x => x.CampaignId).HasMaxLength(50);
            e.Property(x => x.AdAccountId).HasMaxLength(50);
            e.Property(x => x.Name).HasMaxLength(300);
            e.Property(x => x.Status).HasMaxLength(30);
            e.Property(x => x.EffectiveStatus).HasMaxLength(30);
            e.Property(x => x.DailyBudget).HasPrecision(19, 4);
            e.Property(x => x.RemoteVersion).HasMaxLength(100);
            e.HasIndex(x => x.ClientId);
        });
        b.Entity<MetaInsightDailyProj>(e =>
        {
            e.HasKey(x => new { x.CampaignId, x.Date });
            e.Property(x => x.CampaignId).HasMaxLength(50);
            e.Property(x => x.Spend).HasPrecision(19, 4);
            e.Property(x => x.CurrencyCode).HasMaxLength(3).IsUnicode(false);
            e.HasIndex(x => new { x.ClientId, x.Date });
        });
        b.Entity<GhlMessageProj>(e =>
        {
            e.HasKey(x => x.MessageId);
            e.Property(x => x.MessageId).HasMaxLength(100);
            e.Property(x => x.LocationId).HasMaxLength(50);
            e.Property(x => x.ContactId).HasMaxLength(50);
            e.Property(x => x.MessageType).HasMaxLength(30);
            e.Property(x => x.BodyPreview).HasMaxLength(500);
            e.HasIndex(x => new { x.ContactId, x.SentAt });
        });
    }
}
